# Boilerplate code generated by OVITO Pro 3.7.3
from ovito.io import *
from ovito.modifiers import *
from ovito.data import *
from ovito.pipeline import *
import sys

fname = sys.argv[1]

# Data import:
pipeline = import_file(fname)

# Unwrap trajectories:
#pipeline.modifiers.append(UnwrapTrajectoriesModifier())

# Select type:
#pipeline.modifiers.append(SelectTypeModifier(types = {1, 2}))

# Delete selected:
#pipeline.modifiers.append(DeleteSelectedModifier())

#for i in range(pipeline.source.num_frames):
#    export_file(pipeline, f"output.{i}.dump", "lammps/dump", frame=i)

#export_file(pipeline, "branch_pk0.51_T1.0.data", "lammps/data", atom_style="bond", omit_masses=True)
export_file(pipeline, sys.argv[2], "lammps/data", atom_style="full", omit_masses=True)

